### ISSUE TITLE
implement `updateDetails()` function of `campAdmin` class

### ISSUE THREAD

**Issue by suraj-singh12** [suraj-singh12/Project-Rahat#9]
### Only updating the following values is allowed: 

1. `leftOn` : if a person leaves the camp, updating his/her `leftOn` date is allowed.
- _NOTE_ : if `leftOn` date is set, then `inCamp` needs to be set to `N` (i.e. if a person leaves camp, his/her left date is updated alongwith status updated to Not in camp)

2. `injury` : if `injury` == `Y` for a person, then updating the following injury details is allowed :
- `injury_level` : `L`, `N`, `H`, `C` 
- `recovery_initiated` : can only be set to `Y` (if == `N'); if already `Y`, then no modification allowed.
- `recovery_percentage` : `>=0  and <= 100` 

**Tasks :**
- [x] Implement `updateDetails()` function
- [x] Function must have a `query` finally, to make the required changes to person details in database
- [x] Unit test the function
